name: Deploy apps_v2 (Python) to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # adjust if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./apps_v2

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: insureflow2  # your Azure Web App name
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_235A5BE7255747E98F67909DA20A278D }}
          package: ./apps_v2
